// This file is auto-generated by the Supabase CLI
type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      medicamentos: {
        Row: {
          id: number
          created_at: string
          nome: string | null
          user_id: string | null
          dosagem: string | null
          frequencia: Json | null
          quantidade: number | null
          concluido: boolean | null
          data_agendada: string | null
          via: string | null
          ultima_vez_tomado: string | null
          proxima_dose: string | null
          observacoes: string | null
          ativo: boolean | null
        }
        Insert: {
          id?: number
          created_at?: string
          nome?: string | null
          user_id?: string | null
          dosagem?: string | null
          frequencia?: Json | null
          quantidade?: number | null
          concluido?: boolean | null
          data_agendada?: string | null
          via?: string | null
          ultima_vez_tomado?: string | null
          proxima_dose?: string | null
          observacoes?: string | null
          ativo?: boolean | null
        }
        Update: {
          id?: number
          created_at?: string
          nome?: string | null
          user_id?: string | null
          dosagem?: string | null
          frequencia?: Json | null
          quantidade?: number | null
          concluido?: boolean | null
          data_agendada?: string | null
          via?: string | null
          ultima_vez_tomado?: string | null
          proxima_dose?: string | null
          observacoes?: string | null
          ativo?: boolean | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      marcar_medicamento_tomado: {
        Args: {
          medicamento_id: number
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
